// Bundled vehicle reference data for the booking flow's vehicle picker.
//
// Comprehensive but pragmatic — covers ~70 makes and the most-common
// models on US roads from 1990 forward. Not literally every model ever
// shipped (the NHTSA vPIC database has ~10k entries for that), but deep
// enough that a Bay Area client booking a wrap/PPF/tint can almost
// always find their car in the dropdown. The free-text trim field on
// the booking page absorbs anything that isn't here.
//
// Discontinued brands (Mercury, Oldsmobile, Pontiac, Plymouth, Saturn,
// Hummer original, Scion, Saab, Eagle) are kept because their cars are
// still on the road and customers still bring them in. Models within
// each make sorted alphabetically for predictable scrolling.

export const CURRENT_YEAR = 2026;
export const EARLIEST_YEAR = 1990;

export const YEARS = Array.from(
  { length: CURRENT_YEAR - EARLIEST_YEAR + 1 },
  (_, i) => String(CURRENT_YEAR - i)
);

export const MAKES = [
  "Acura", "Alfa Romeo", "Aston Martin", "Audi",
  "Bentley", "BMW", "Bugatti", "Buick",
  "Cadillac", "Chevrolet", "Chrysler",
  "Dodge",
  "Eagle",
  "Ferrari", "Fiat", "Fisker", "Ford",
  "Genesis", "GMC",
  "Honda", "Hummer", "Hyundai",
  "Infiniti",
  "Jaguar", "Jeep",
  "Karma", "Kia", "Koenigsegg",
  "Lamborghini", "Land Rover", "Lexus", "Lincoln",
  "Lotus", "Lucid",
  "Maserati", "Maybach", "Mazda", "McLaren",
  "Mercedes-Benz", "Mercury", "Mini", "Mitsubishi",
  "Nissan",
  "Oldsmobile",
  "Pagani", "Plymouth", "Polestar", "Pontiac", "Porsche",
  "Ram", "Rivian", "Rolls-Royce",
  "Saab", "Saturn", "Scion", "Smart", "Subaru", "Suzuki",
  "Tesla", "Toyota",
  "Vinfast", "Volkswagen", "Volvo",
];

export const MODELS = {
  Acura: [
    "CDX", "CL", "EL", "ILX", "Integra", "Integra Type S", "Legend",
    "MDX", "MDX Type S", "NSX", "RDX", "RL", "RLX", "RSX", "SLX",
    "TL", "TLX", "TLX Type S", "TSX", "Vigor", "ZDX",
  ],
  "Alfa Romeo": [
    "4C", "8C Competizione", "Giulia", "Giulia Quadrifoglio", "Spider",
    "Stelvio", "Stelvio Quadrifoglio", "Tonale",
  ],
  "Aston Martin": [
    "DB7", "DB9", "DB11", "DB12", "DBS", "DBS Superleggera", "DBX",
    "One-77", "Rapide", "V8 Vantage", "V12 Vantage", "Valkyrie",
    "Vanquish", "Vantage", "Virage", "Vulcan",
  ],
  Audi: [
    "80", "100", "200", "A3", "A4", "A5", "A6", "A7", "A8", "allroad",
    "e-tron", "e-tron GT", "Q3", "Q4 e-tron", "Q5", "Q5 e-tron",
    "Q6 e-tron", "Q7", "Q8", "Q8 e-tron", "R8", "RS3", "RS4", "RS5",
    "RS6", "RS7", "RS Q3", "RS Q8", "S3", "S4", "S5", "S6", "S7", "S8",
    "SQ5", "SQ7", "SQ8", "TT", "TT RS", "TTS",
  ],
  Bentley: [
    "Arnage", "Azure", "Bentayga", "Brooklands", "Continental",
    "Continental Flying Spur", "Continental GT", "Continental GTC",
    "Continental Supersports", "Flying Spur", "Mulsanne", "Turbo R",
  ],
  BMW: [
    "1 Series", "128i", "135i", "1M",
    "2 Series", "228i", "230i", "235i", "240i", "M240i", "M2", "2002",
    "3 Series", "318i", "320i", "323i", "325i", "328i", "330i", "335i",
    "340i", "M340i", "M3",
    "4 Series", "428i", "430i", "435i", "440i", "M440i", "M4",
    "5 Series", "525i", "528i", "530i", "535i", "540i", "545i", "550i",
    "M550i", "M5",
    "6 Series", "640i", "645i", "650i", "M6",
    "7 Series", "730i", "735i", "740i", "745i", "750i", "760i", "M760i",
    "8 Series", "840i", "850i", "M8",
    "i3", "i4", "i5", "i7", "i8", "iX",
    "X1", "X2", "X3", "X3 M", "X4", "X4 M", "X5", "X5 M", "X6", "X6 M",
    "X7", "XM",
    "Z3", "Z4", "Z8",
  ],
  Bugatti: [
    "Chiron", "Divo", "EB110", "Mistral", "Tourbillon", "Veyron",
  ],
  Buick: [
    "Cascada", "Century", "Enclave", "Encore", "Encore GX", "Envision",
    "Envista", "LaCrosse", "LeSabre", "Lucerne", "Park Avenue",
    "Rainier", "Regal", "Rendezvous", "Riviera", "Roadmaster", "Skylark",
    "Terraza", "Verano",
  ],
  Cadillac: [
    "ATS", "ATS-V", "CT4", "CT4-V", "CT4-V Blackwing", "CT5", "CT5-V",
    "CT5-V Blackwing", "CT6", "CT6-V", "CTS", "CTS-V", "DeVille", "DTS",
    "ELR", "Eldorado", "Escalade", "Escalade ESV", "Escalade-V",
    "Fleetwood", "LYRIQ", "Seville", "SRX", "STS", "XLR", "XT4", "XT5",
    "XT6", "XTS",
  ],
  Chevrolet: [
    "Astro", "Avalanche", "Aveo", "Beretta", "Blazer", "Bolt", "Bolt EUV",
    "Camaro", "Camaro Z/28", "Camaro ZL1", "Caprice", "Captiva",
    "Cavalier", "Cobalt", "Cobalt SS", "Colorado", "Colorado ZR2",
    "Corsica", "Corvette", "Corvette Stingray", "Corvette Z06",
    "Corvette ZR1", "Corvette E-Ray", "Cruze", "Equinox", "Express",
    "HHR", "Impala", "Lumina", "Malibu", "Monte Carlo", "Prizm", "S-10",
    "Silverado", "Silverado 1500", "Silverado 2500HD", "Silverado 3500HD",
    "Silverado EV", "Sonic", "Spark", "SS", "SSR", "Suburban", "Tahoe",
    "Tracker", "Trailblazer", "Traverse", "Trax", "Uplander", "Venture",
    "Volt",
  ],
  Chrysler: [
    "200", "300", "300C", "300M", "Aspen", "Concorde", "Crossfire",
    "LHS", "New Yorker", "Pacifica", "PT Cruiser", "Sebring",
    "Town & Country", "Voyager",
  ],
  Dodge: [
    "Avenger", "Caliber", "Caravan", "Challenger", "Challenger Hellcat",
    "Challenger SRT Demon", "Charger", "Charger Daytona", "Charger Hellcat",
    "Charger SRT Demon", "Dakota", "Dart", "Durango", "Durango Hellcat",
    "Durango SRT", "Grand Caravan", "Hornet", "Intrepid", "Journey",
    "Magnum", "Magnum SRT8", "Neon", "Nitro", "Stealth", "Stratus",
    "Viper",
  ],
  Eagle: ["Premier", "Summit", "Talon", "Vision"],
  Ferrari: [
    "296 GTB", "296 GTS", "360 Modena", "360 Spider", "430 Scuderia",
    "458 Italia", "458 Speciale", "458 Spider", "488 GTB", "488 Pista",
    "488 Spider", "599 GTB", "612 Scaglietti", "812 Competizione",
    "812 GTS", "812 Superfast", "California", "California T",
    "Daytona SP3", "Enzo", "F12berlinetta", "F12tdf", "F355", "F40",
    "F50", "F8 Tributo", "F8 Spider", "FF", "GTC4Lusso", "LaFerrari",
    "Monza SP1", "Monza SP2", "Portofino", "Portofino M", "Purosangue",
    "Roma", "Roma Spider", "SF90 Spider", "SF90 Stradale", "SF90 XX",
    "Testarossa",
  ],
  Fiat: [
    "124 Spider", "500", "500 Abarth", "500e", "500L", "500X",
    "Abarth 124 Spider",
  ],
  Fisker: ["Karma", "Ocean"],
  Ford: [
    "Bronco", "Bronco Raptor", "Bronco Sport", "C-Max", "Contour",
    "Crown Victoria", "EcoSport", "Edge", "Escape", "Escort", "Excursion",
    "Expedition", "Explorer", "F-150", "F-150 Lightning", "F-150 Raptor",
    "F-150 Raptor R", "F-250", "F-350", "Fairmont", "Fiesta", "Fiesta ST",
    "Five Hundred", "Flex", "Focus", "Focus RS", "Focus ST", "Fusion",
    "GT", "Maverick", "Mustang", "Mustang Bullitt", "Mustang Cobra",
    "Mustang Dark Horse", "Mustang Mach 1", "Mustang Mach-E",
    "Mustang Shelby GT350", "Mustang Shelby GT500", "Probe", "Ranger",
    "Ranger Raptor", "Taurus", "Taurus SHO", "Thunderbird", "Transit",
    "Transit Connect",
  ],
  Genesis: [
    "G70", "G80", "G80 EV", "G90", "GV60", "GV70", "GV70 EV", "GV80",
  ],
  GMC: [
    "Acadia", "Canyon", "Canyon AT4X", "Envoy", "Hummer EV Pickup",
    "Hummer EV SUV", "Jimmy", "Safari", "Savana", "Sierra",
    "Sierra 1500", "Sierra 2500HD", "Sierra 3500HD", "Sierra Denali",
    "Sonoma", "Suburban", "Terrain", "Yukon", "Yukon Denali", "Yukon XL",
  ],
  Honda: [
    "Accord", "Accord Hybrid", "Civic", "Civic Hybrid", "Civic Si",
    "Civic Type R", "Clarity", "CR-V", "CR-V Hybrid", "CR-Z", "CRX",
    "Crosstour", "del Sol", "Element", "Fit", "HR-V", "Insight",
    "Odyssey", "Passport", "Pilot", "Prelude", "Ridgeline", "S2000",
  ],
  Hummer: ["H1", "H2", "H3", "H3T"],
  Hyundai: [
    "Accent", "Azera", "Elantra", "Elantra GT", "Elantra N", "Equus",
    "Genesis", "Genesis Coupe", "Ioniq", "Ioniq 5", "Ioniq 5 N",
    "Ioniq 6", "Kona", "Kona Electric", "Kona N", "Nexo", "Palisade",
    "Santa Cruz", "Santa Fe", "Sonata", "Sonata N Line", "Tiburon",
    "Tucson", "Veloster", "Veloster N", "Venue", "XG350",
  ],
  Infiniti: [
    "EX", "FX", "G", "G35", "G37", "I30", "I35", "J30", "JX", "M30",
    "M35", "M37", "M45", "Q30", "Q40", "Q45", "Q50", "Q60", "Q70",
    "QX30", "QX50", "QX55", "QX56", "QX60", "QX70", "QX80",
  ],
  Jaguar: [
    "E-Pace", "F-Pace", "F-Pace SVR", "F-Type", "F-Type R", "F-Type SVR",
    "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ", "XJR", "XK", "XKR",
  ],
  Jeep: [
    "Cherokee", "Comanche", "Commander", "Compass", "Gladiator",
    "Grand Cherokee", "Grand Cherokee 4xe", "Grand Cherokee L",
    "Grand Cherokee SRT", "Grand Cherokee Trackhawk", "Grand Wagoneer",
    "Liberty", "Patriot", "Renegade", "Wagoneer", "Wrangler",
    "Wrangler 4xe", "Wrangler Rubicon", "Wrangler Rubicon 392",
  ],
  Karma: ["GS-6", "Revero"],
  Kia: [
    "Cadenza", "Carnival", "EV6", "EV6 GT", "EV9", "Forte", "K5", "K900",
    "Niro", "Niro EV", "Optima", "Rio", "Rondo", "Seltos", "Sedona",
    "Sorento", "Soul", "Spectra", "Sportage", "Stinger", "Telluride",
  ],
  Koenigsegg: [
    "Agera", "Agera R", "Agera RS", "CC8S", "CCX", "CCXR", "Gemera",
    "Jesko", "One:1", "Regera",
  ],
  Lamborghini: [
    "Aventador", "Aventador SV", "Aventador SVJ", "Centenario", "Diablo",
    "Gallardo", "Huracán", "Huracán EVO", "Huracán Performante",
    "Huracán STO", "Huracán Sterrato", "Huracán Tecnica", "Murciélago",
    "Reventón", "Revuelto", "Sián", "Urus", "Urus Performante",
    "Urus SE", "Veneno",
  ],
  "Land Rover": [
    "Defender", "Defender 90", "Defender 110", "Discovery",
    "Discovery Sport", "Freelander", "LR2", "LR3", "LR4", "Range Rover",
    "Range Rover Evoque", "Range Rover Sport", "Range Rover Sport SVR",
    "Range Rover SV", "Range Rover Velar",
  ],
  Lexus: [
    "CT", "ES", "GS", "GS F", "GX", "IS", "IS F", "IS500", "LC", "LC500",
    "LC500h", "LFA", "LS", "LX", "NX", "RC", "RC F", "RX", "RZ", "SC",
    "TX", "UX",
  ],
  Lincoln: [
    "Aviator", "Continental", "Corsair", "MKC", "MKS", "MKT", "MKX",
    "MKZ", "Mark LT", "Mark VIII", "Nautilus", "Navigator", "Town Car",
    "Zephyr",
  ],
  Lotus: ["Elise", "Eletre", "Emira", "Esprit", "Evija", "Evora", "Exige"],
  Lucid: [
    "Air", "Air Dream Edition", "Air Grand Touring", "Air Pure",
    "Air Sapphire", "Air Touring", "Gravity",
  ],
  Maserati: [
    "3200 GT", "Coupe", "GranCabrio", "Ghibli", "GranSport",
    "GranTurismo", "GranTurismo Folgore", "Grecale", "Levante", "MC20",
    "MC20 Cielo", "Quattroporte", "Spyder",
  ],
  Maybach: ["57", "62", "S-Class", "S-Class Pullman", "GLS"],
  Mazda: [
    "2", "3", "3 Hatchback", "6", "323", "626", "929", "Cosmo", "CX-3",
    "CX-30", "CX-5", "CX-50", "CX-7", "CX-70", "CX-9", "CX-90", "Miata",
    "Millenia", "MPV", "MX-3", "MX-5", "MX-6", "MX-30", "Navajo",
    "Protege", "Protege5", "RX-7", "RX-8", "Tribute",
  ],
  McLaren: [
    "540C", "570S", "570S Spider", "600LT", "600LT Spider", "620R", "650S",
    "650S Spider", "675LT", "720S", "720S Spider", "750S", "750S Spider",
    "765LT", "765LT Spider", "Artura", "Elva", "F1", "GT", "MP4-12C",
    "P1", "Senna", "Senna GTR", "Speedtail",
  ],
  "Mercedes-Benz": [
    "190", "240D", "300CE", "300E", "300SD", "300SE", "300SL", "400E",
    "500E", "560SEL",
    "A-Class", "A35 AMG", "A45 AMG",
    "AMG GT", "AMG GT 4-Door", "AMG GT Black Series", "AMG GT C",
    "AMG GT R", "AMG GT S", "AMG One",
    "B-Class",
    "C-Class", "C32 AMG", "C36 AMG", "C43 AMG", "C55 AMG", "C63 AMG",
    "C63 S AMG",
    "CL-Class", "CL500", "CL550", "CL55 AMG", "CL63 AMG", "CL65 AMG",
    "CLA-Class", "CLA45 AMG",
    "CLK-Class", "CLK500", "CLK55 AMG", "CLK63 AMG", "CLK63 AMG Black",
    "CLS-Class", "CLS500", "CLS55 AMG", "CLS63 AMG",
    "E-Class", "E320", "E350", "E400", "E430", "E500", "E550", "E55 AMG",
    "E63 AMG", "E63 S AMG",
    "EQA", "EQB", "EQE", "EQE SUV", "EQS", "EQS SUV", "EQT", "EQV",
    "G-Class", "G500", "G55 AMG", "G63 AMG", "G65 AMG",
    "GLA-Class", "GLA45 AMG",
    "GLB-Class", "GLB35 AMG",
    "GLC-Class", "GLC43 AMG", "GLC63 AMG", "GLC63 S AMG",
    "GLE-Class", "GLE43 AMG", "GLE53 AMG", "GLE63 AMG", "GLE63 S AMG",
    "GLK-Class",
    "GLS-Class", "GLS580", "GLS63 AMG",
    "M-Class", "ML320", "ML350", "ML500", "ML55 AMG", "ML63 AMG",
    "R-Class",
    "S-Class", "S400", "S500", "S550", "S560", "S580", "S600", "S63 AMG",
    "S65 AMG",
    "SL-Class", "SL500", "SL550", "SL55 AMG", "SL63 AMG", "SL65 AMG",
    "SL65 AMG Black", "SLC-Class", "SLK-Class", "SLR McLaren", "SLS AMG",
    "Sprinter",
  ],
  Mercury: [
    "Cougar", "Grand Marquis", "Marauder", "Mariner", "Milan", "Montego",
    "Monterey", "Mountaineer", "Mystique", "Sable", "Tracer", "Villager",
  ],
  Mini: [
    "Cooper", "Cooper Clubman", "Cooper Convertible", "Cooper Countryman",
    "Cooper Hardtop", "Cooper Hardtop 4-Door", "Cooper JCW",
    "Cooper JCW Countryman", "Cooper S", "Cooper SE", "Coupe", "Paceman",
    "Roadster",
  ],
  Mitsubishi: [
    "3000GT", "3000GT VR-4", "Diamante", "Eclipse", "Eclipse Cross",
    "Endeavor", "Galant", "Lancer", "Lancer Evolution", "Lancer Ralliart",
    "Mirage", "Mirage G4", "Montero", "Montero Sport", "Outlander",
    "Outlander PHEV", "Outlander Sport", "Raider", "Starion",
  ],
  Nissan: [
    "200SX", "240SX", "300ZX", "350Z", "370Z", "Altima", "Altima Hybrid",
    "Armada", "Cube", "Frontier", "GT-R", "GT-R Nismo", "Juke",
    "Juke Nismo", "Kicks", "Leaf", "Maxima", "Murano", "NV200", "Pathfinder",
    "Pulsar", "Quest", "Rogue", "Rogue Sport", "Sentra", "Sentra SE-R",
    "Skyline", "Titan", "Titan XD", "Versa", "Xterra", "Z",
  ],
  Oldsmobile: [
    "Achieva", "Alero", "Aurora", "Bravada", "Cutlass", "Cutlass Calais",
    "Cutlass Cruiser", "Cutlass Supreme", "Eighty-Eight", "Intrigue",
    "LSS", "Ninety-Eight", "Regency", "Silhouette",
  ],
  Pagani: ["Huayra", "Utopia", "Zonda"],
  Plymouth: [
    "Acclaim", "Breeze", "Grand Voyager", "Laser", "Neon", "Prowler",
    "Sundance", "Voyager",
  ],
  Polestar: ["1", "2", "3", "4", "5"],
  Pontiac: [
    "Aztek", "Bonneville", "Catalina", "Firebird", "Firebird Trans Am",
    "G3", "G5", "G6", "G8", "Grand Am", "Grand Prix", "GTO", "Montana",
    "Solstice", "Solstice GXP", "Sunbird", "Sunfire", "Torrent",
    "Trans Sport", "Vibe",
  ],
  Porsche: [
    "718 Boxster", "718 Boxster GTS", "718 Boxster Spyder", "718 Cayman",
    "718 Cayman GT4", "718 Cayman GT4 RS", "718 Cayman GTS",
    "911", "911 Carrera", "911 Carrera 4", "911 Carrera 4 GTS",
    "911 Carrera 4S", "911 Carrera GT", "911 Carrera GTS",
    "911 Carrera S", "911 Carrera T", "911 Dakar", "911 GT2",
    "911 GT2 RS", "911 GT3", "911 GT3 RS", "911 GT3 Touring",
    "911 R", "911 S/T", "911 Sport Classic", "911 Targa",
    "911 Targa 4 GTS", "911 Turbo", "911 Turbo S",
    "928", "944", "968",
    "Boxster", "Boxster Spyder",
    "Carrera GT",
    "Cayenne", "Cayenne Coupe", "Cayenne GTS", "Cayenne S",
    "Cayenne Turbo", "Cayenne Turbo GT", "Cayenne Turbo S E-Hybrid",
    "Cayman", "Cayman GT4", "Cayman GTS", "Cayman R", "Cayman S",
    "Macan", "Macan Electric", "Macan GTS", "Macan S", "Macan Turbo",
    "Panamera", "Panamera 4S", "Panamera GTS", "Panamera Turbo",
    "Panamera Turbo S",
    "Taycan", "Taycan 4S", "Taycan Cross Turismo", "Taycan GTS",
    "Taycan Sport Turismo", "Taycan Turbo", "Taycan Turbo GT",
    "Taycan Turbo S",
  ],
  Ram: [
    "1500", "1500 Classic", "1500 Rebel", "1500 TRX", "2500", "2500 Power Wagon",
    "3500", "C/V", "ProMaster", "ProMaster City",
  ],
  Rivian: ["R1S", "R1T"],
  "Rolls-Royce": [
    "Black Badge", "Cullinan", "Dawn", "Ghost", "Phantom", "Silver Seraph",
    "Spectre", "Wraith",
  ],
  Saab: ["9-2X", "9-3", "9-3 Aero", "9-5", "9-7X", "900", "9000"],
  Saturn: [
    "Astra", "Aura", "Ion", "L-Series", "Outlook", "Relay", "S-Series",
    "Sky", "Sky Red Line", "Vue",
  ],
  Scion: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  Smart: ["ForFour", "ForTwo", "ForTwo Electric Drive"],
  Subaru: [
    "Ascent", "Baja", "BRZ", "BRZ tS", "Crosstrek", "Forester",
    "Forester XT", "Impreza", "Impreza WRX", "Impreza WRX STI", "Justy",
    "Legacy", "Legacy GT", "Loyale", "Outback", "Outback XT", "Solterra",
    "STI", "SVX", "Tribeca", "WRX", "WRX STI",
  ],
  Suzuki: [
    "Aerio", "Equator", "Esteem", "Forenza", "Grand Vitara", "Kizashi",
    "Reno", "Samurai", "Sidekick", "SX4", "Verona", "Vitara", "X-90",
  ],
  Tesla: [
    "Cybertruck", "Model 3", "Model 3 Long Range", "Model 3 Performance",
    "Model S", "Model S Long Range", "Model S Plaid", "Model X",
    "Model X Long Range", "Model X Plaid", "Model Y", "Model Y Long Range",
    "Model Y Performance", "Roadster (2008-2012)", "Roadster (next-gen)",
    "Semi",
  ],
  Toyota: [
    "4Runner", "86", "Avalon", "Avalon Hybrid", "Camry", "Camry Hybrid",
    "Celica", "Celica GT-S", "Corolla", "Corolla Cross", "Corolla Hatchback",
    "Corolla Hybrid", "Crown", "FJ Cruiser", "GR86", "GR Corolla",
    "GR Supra", "Highlander", "Highlander Hybrid", "Land Cruiser", "Matrix",
    "MR2", "MR2 Spyder", "Mirai", "Paseo", "Previa", "Prius",
    "Prius Prime", "RAV4", "RAV4 Hybrid", "RAV4 Prime", "Sequoia",
    "Sienna", "Solara", "Supra", "Supra Turbo", "Tacoma", "Tacoma TRD",
    "Tercel", "Tundra", "Venza", "Yaris",
  ],
  Vinfast: ["VF6", "VF7", "VF8", "VF9"],
  Volkswagen: [
    "Arteon", "Atlas", "Atlas Cross Sport", "Beetle", "Cabrio", "CC",
    "Corrado", "Eos", "EuroVan", "Fox", "Golf", "Golf GTI", "Golf R",
    "Golf SportWagen", "ID.4", "ID.Buzz", "Jetta", "Jetta GLI",
    "Karmann Ghia", "New Beetle", "Passat", "Phaeton", "Polo", "Rabbit",
    "Routan", "Tiguan", "Touareg", "Vento",
  ],
  Volvo: [
    "240", "760", "850", "940", "960", "C30", "C40", "C70", "EC40", "EX30",
    "EX40", "EX90", "S40", "S60", "S60 Polestar", "S70", "S80", "S90",
    "V40", "V50", "V60", "V60 Cross Country", "V70", "V90",
    "V90 Cross Country", "XC40", "XC60", "XC70", "XC90",
  ],
};
